version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/basic/java/dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: