FROM openjdk:17-jdk-slim

WORKDIR /app

# 複製 Maven Wrapper 和 pom.xml
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

# 下載依賴項
RUN ./mvnw dependency:go-offline

# 複製源代碼
COPY src ./src

# 使用 Maven Wrapper 構建應用
RUN ./mvnw package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/springboot_proto-0.0.1-SNAPSHOT.jar"]