FROM openjdk:17-jdk-slim

WORKDIR /app

# 複製 Maven Wrapper 和 pom.xml
COPY src/springboot_proto/.mvn/ .mvn/
COPY src/springboot_proto/mvnw src/springboot_proto/pom.xml ./

# 下載依賴項
RUN ./mvnw dependency:go-offline

# 複製源代碼
COPY src/springboot_proto/src ./src

# 使用 Maven Wrapper 構建應用
RUN ./mvnw package -DskipTests

RUN ls -R /app
RUN find /app -name "*.jar"

EXPOSE 8080

CMD ["sh", "-c", "ls -R /app && find /app -name '*.jar' && java -jar target/springboot_proto-0.0.1-SNAPSHOT.jar"]